component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/net/.*
- ./bin/net/sf/.*
- ./bin/net/sf/freecol/.*
- ./bin/net/sf/freecol/client/.*
- ./bin/net/sf/freecol/client/control/.*
- ./bin/net/sf/freecol/client/gui/.*
- ./bin/net/sf/freecol/client/gui/action/.*
- ./bin/net/sf/freecol/client/gui/animation/.*
- ./bin/net/sf/freecol/client/gui/i18n/.*
- ./bin/net/sf/freecol/client/gui/menu/.*
- ./bin/net/sf/freecol/client/gui/option/.*
- ./bin/net/sf/freecol/client/gui/panel/.*
- ./bin/net/sf/freecol/client/gui/plaf/.*
- ./bin/net/sf/freecol/client/gui/sound/.*
- ./bin/net/sf/freecol/client/gui/video/.*
- ./bin/net/sf/freecol/client/networking/.*
- ./bin/net/sf/freecol/common/.*
- ./bin/net/sf/freecol/common/io/.*
- ./bin/net/sf/freecol/common/io/sza/.*
- ./bin/net/sf/freecol/common/logging/.*
- ./bin/net/sf/freecol/common/model/.*
- ./bin/net/sf/freecol/common/model/mission/.*
- ./bin/net/sf/freecol/common/model/pathfinding/.*
- ./bin/net/sf/freecol/common/networking/.*
- ./bin/net/sf/freecol/common/option/.*
- ./bin/net/sf/freecol/common/util/.*
- ./bin/net/sf/freecol/metaserver/.*
- ./bin/net/sf/freecol/server/.*
- ./bin/net/sf/freecol/server/ai/.*
- ./bin/net/sf/freecol/server/ai/goal/.*
- ./bin/net/sf/freecol/server/ai/mission/.*
- ./bin/net/sf/freecol/server/control/.*
- ./bin/net/sf/freecol/server/generator/.*
- ./bin/net/sf/freecol/server/model/.*
- ./bin/net/sf/freecol/server/networking/.*
- ./bin/net/sf/freecol/tools/.*
- ./bin/net/sf/freecol/util/.*
- ./bin/net/sf/freecol/util/test/.*
- ./build/.*
- ./build/bin/.*
- ./build/bin/native/.*
- ./build/bin/native/izpack/.*
- ./build/installer/.*
- ./build/jars/.*
- ./build/skeletons/.*
- ./build/skeletons/console-wrapper/.*
- ./build/skeletons/windowed-wrapper/.*
- ./config/.*
- ./config/Eclipse/.*
- ./config/nbproject/.*
- ./data/.*
- ./data/base/.*
- ./data/maps/.*
- ./data/mods/.*
- ./data/mods/classic_ui/.*
- ./data/mods/example/.*
- ./data/mods/hutzli/.*
- ./data/mods/misiulo/.*
- ./data/mods/plantForest/.*
- ./data/mods/plantForest/order-buttons/.*
- ./data/mods/plantForest/order-buttons/disabled/.*
- ./data/mods/plantForest/order-buttons/highlighted/.*
- ./data/mods/plantForest/order-buttons/normal/.*
- ./data/mods/plantForest/order-buttons/pressed/.*
- ./data/rules/.*
- ./data/rules/classic/.*
- ./data/rules/freecol/.*
- ./data/rules/testing/.*
- ./data/strings/.*
- ./doc/.*
- ./doc/images/.*
- ./jars/.*
- ./packaging/.*
- ./packaging/common/.*
- ./packaging/common/Uninstaller/.*
- ./packaging/debian/.*
- ./packaging/gentoo/.*
- ./packaging/icons/.*
- ./packaging/targz/.*
- ./schema/.*
- ./schema/data/.*
- ./test/.*
- ./test/lib/.*
